### ISSUE TITLE
Can't build example, linking error

### ISSUE THREAD

**Issue by sencrash** [b1naryth1ef/dscord#33] opened 2019-09-06 08:09 UTC
dub build

Running pre-generate commands for vibe-d:tls...
Performing "debug" build using /home/scrash/dlang/dmd-2.088.0/linux/bin64/dmd for x86_64.
opus 0.0.3: target for configuration "opus-dynamic" is up to date.
dcad 0.0.10: target for configuration "library" is up to date.
shaker 0.0.8: target for configuration "shaker-static-x64" is up to date.
taggedalgebraic 0.11.4: target for configuration "library" is up to date.
eventcore 0.8.46: target for configuration "epoll" is up to date.
stdx-allocator 2.77.5: target for configuration "library" is up to date.
vibe-core 1.6.2: target for configuration "epoll" is up to date.
vibe-d:utils 0.8.5: target for configuration "library" is up to date.
vibe-d:data 0.8.5: target for configuration "library" is up to date.
diet-ng 1.6.0: target for configuration "library" is up to date.
mir-linux-kernel 1.0.1: target for configuration "library" is up to date.
vibe-d:crypto 0.8.5: target for configuration "library" is up to date.
vibe-d:stream 0.8.5: target for configuration "library" is up to date.
vibe-d:textfilter 0.8.5: target for configuration "library" is up to date.
vibe-d:inet 0.8.5: target for configuration "library" is up to date.
vibe-d:tls 0.8.5: target for configuration "openssl" is up to date.
vibe-d:http 0.8.5: target for configuration "library" is up to date.
dscord 1.0.0-beta.1: target for configuration "dscord-linux-static-x64" is up to date.
dscord-examples ~master: building configuration "dscord-examples-linux-static-x64"...
CommandConfig(["ping"]) onPing
CommandConfig(["embed"])        onEmbed
CommandConfig(["clear"])        onClearMessages
CommandConfig(["whereami"])     onWhereAmI
CommandConfig(["spam"]) spam
/home/scrash/.dub/packages/vibe-d-0.8.5/vibe-d/utils/vibe/utils/dictionarylist.d(77,22): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/home/scrash/.dub/packages/vibe-d-0.8.5/vibe-d/utils/vibe/utils/dictionarylist.d(77,22): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/home/scrash/.dub/packages/vibe-d-0.8.5/vibe-d/utils/vibe/utils/dictionarylist.d(77,22): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/home/scrash/.dub/packages/vibe-d-0.8.5/vibe-d/utils/vibe/utils/dictionarylist.d(77,22): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/home/scrash/dlang/dmd-2.088.0/linux/bin64/../../src/phobos/std/range/primitives.d(174,38): Deprecation: alias byKeyValue this is 
deprecated - Iterate over .byKeyValue instead.
/home/scrash/dlang/dmd-2.088.0/linux/bin64/../../src/phobos/std/range/primitives.d(176,27): Deprecation: alias byKeyValue this is 
deprecated - Iterate over .byKeyValue instead.
/home/scrash/dlang/dmd-2.088.0/linux/bin64/../../src/phobos/std/range/primitives.d(174,38): Deprecation: alias byKeyValue this is 
deprecated - Iterate over .byKeyValue instead.
/home/scrash/dlang/dmd-2.088.0/linux/bin64/../../src/phobos/std/range/primitives.d(176,27): Deprecation: alias byKeyValue this is 
deprecated - Iterate over .byKeyValue instead.
/home/scrash/.dub/packages/vibe-d-0.8.5/vibe-d/utils/vibe/utils/dictionarylist.d(77,22): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/home/scrash/.dub/packages/vibe-d-0.8.5/vibe-d/utils/vibe/utils/dictionarylist.d(77,22): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
Linking...
/usr/bin/ld: cannot find -lopus
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
/home/scrash/dlang/dmd-2.088.0/linux/bin64/dmd failed with exit code 1.

**Comment by polygonalenippel** [comment] 2019-09-23 08:26
duplicate of #32

**Comment by sencrash** [comment] 2019-09-24 11:42
? You have no description in your issue, how is this a duplicate

**Closed as completed** 2020-06-01 14:01 UTC
